"""add status attribute to Movie and TVShow models

Revision ID: 25eb26ac249f
Revises: f2af0c3d92ca
Create Date: 2025-01-28 16:15:01.091108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25eb26ac249f'
down_revision = 'f2af0c3d92ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='discoverable'))

    with op.batch_alter_table('tv_shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='discoverable'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_shows', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
