"""add created_at attribute to MovieWatchEvent and TVShowWatchEvent models

Revision ID: 97f1f6906dc1
Revises: 25eb26ac249f
Create Date: 2025-01-28 20:51:51.984599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f1f6906dc1'
down_revision = '25eb26ac249f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_watch_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('tv_show_watch_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tv_shows', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), server_default=sa.text("'discoverable'"), nullable=False))

    with op.batch_alter_table('tv_show_watch_events', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), server_default=sa.text("'discoverable'"), nullable=False))

    with op.batch_alter_table('movie_watch_events', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
