"""remove UniqueConstraint from MovieWatchEvent and TVShowWatchEvent

Revision ID: 9fd5a3b2b597
Revises: 97f1f6906dc1
Create Date: 2025-01-29 04:21:50.146005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd5a3b2b597'
down_revision = '97f1f6906dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_watch_events', schema=None) as batch_op:
        batch_op.drop_constraint('no_duplicate_user_and_movie_instance', type_='unique')

    with op.batch_alter_table('tv_show_watch_events', schema=None) as batch_op:
        batch_op.drop_constraint('no_duplicate_user_and_tv_show_instance', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_show_watch_events', schema=None) as batch_op:
        batch_op.create_unique_constraint('no_duplicate_user_and_tv_show_instance', ['user_id', 'tv_show_id'])

    with op.batch_alter_table('movie_watch_events', schema=None) as batch_op:
        batch_op.create_unique_constraint('no_duplicate_user_and_movie_instance', ['user_id', 'movie_id'])

    # ### end Alembic commands ###
